### ISSUE TITLE
Wait X seconds after ISL goes UP or DOWN before we start issue reroutes

### ISSUE THREAD

**Issue by nikitacherevko** [telstra/open-kilda#1191]
### Problem: 
From time to time we observe some bouncing ISLs and for every event we perform attempts to evacuate active flows from these ISLs or to reroute DOWN flows to build them through newly discovered ISLs. Because of that we have a bunch of reroutes which redundantly load entire system.

### How it can be solved
We can implement a "sliding window" for all events and we will be able to process all events together after we get a "stable" network. In other words we should wait X seconds before passing such events to TE. It can be implemented as new bolt in event (wfm) topology that will collect all events and wait some time before sending it for further processing.

**Important**
We need to provide limit of window size, so window won't be too large. In other words "max_duration" is needed to prevent not sending messages further to KafkaBolt in case when we are receiving message infinitely and every time we reset time counter, so event topology might not send events at all. 

### Initial diagram:
![image](https://user-images.githubusercontent.com/6116378/44534988-b2b7dc80-a701-11e8-9553-ecb9ce897631.png)

**Comment by nikitacherevko** [comment]
Another idea how it may be implemented to prevent multiple reroutes for the same flow and updating the state of the network once we received update (in previous proposal we wait some time before updating data in neo4j):

![image](https://user-images.githubusercontent.com/6116378/44568827-0f0e1100-a781-11e8-88ad-306e284f3050.png)

**Comment by nikitacherevko** [comment]
Please note: actually we don't do a reroute of down flows on ISL discovered event in CacheBolt, we do it on NetworkChange event received from TE

**Comment by ylobankov** [comment]
**Possible scenario to verify this functionality on staging:**
1. Create N flows, for example, 10 ones.
2. Remember all flows somehow.
3. Make one of the links blink, for example, 5 times. The link should be chosen so that all flows are built through this link. Blinking the link can be made via A-switch.
4. Verify that the number of messages in Kafka is equal to the number of flows, i.e. 10. Without the fix, the number of messages in Kafka should be 50 at least.
5. Wait for some time.
6. Verify that all flows were rerouted and all flows are built not through the blinking link.

**Comment by sergii-iakovenko** [comment]
@IlyaMoiseev Was it resolved along with #1192?

**Comment by IlyaMoiseev** [comment]
Closed with #1192. Improving in #1212
