### ISSUE TITLE
History service

### ISSUE THREAD

**Issue by shusyaM** [telstra/open-kilda#1195]
Objects: Flow, Link, Switch (with ports)

APIs
- /flows/<flow_id>/history
- /switches/<sw_id>/history
- /switches/<sw_id>/port/<port_id>/history
- /links/history/

Data to store
- actor/initiator (who performed action)
- timestamp
- path
- latency
- why was that path chosen
- Action
- reason for reroute (manual, ISL outage, etc.). As much as we can 
- end-to-end cost
- Flow details (bw, etc.) literally do a full flow object snapshot

Blocked by #1127 and #1128 
Epic #472 

#### History records type
History records has 2 types:
- Object Action. When Actor try to change the object.
- Object Event. When Kilda doing something with the object.

Object Action is the cause for subsequent Object Events.
#### History collection
Places to collect history logs:
- User actions in NB
- Sending changes to Speaker
- Write to DB
- (optional) Log results from Speaker (in H&S).

Here is history collections process for `Port down`. User ask `Port down` via NB, this is an action for history. Please, pay attention to work with History DB. Port down workflow was presented as example and may be not correlated with real workflow.
![historyexample](https://user-images.githubusercontent.com/1427656/50217523-2eacf300-0389-11e9-8d05-8374d7f6bbb1.png)

The other case: FloodLight realise that ISL goes down and start reroutes. In that case `ISL down` is an action for history.
![historyexampleinternal](https://user-images.githubusercontent.com/1427656/50217531-310f4d00-0389-11e9-8723-9ccfcf443998.png)

#### General log data
The history will be collected for 4 types of entity: flow, switch, port, link.
Each type of history event must have the following fields:
- actor/initiator
- timestamp
- object ID (can be composite: swithId & portId for port object, 4 fields for link)
- action
- status
- correlation ID
- task ID
- details (text for user, can be used as reason)
- affected flows
#### Type specific fields
For flow:
- forward cookie
- reverse cookie
- src/dst switch/port/vlan
- forward meterId
- reverse meterId
- bandwidth (the value or null if it ignored)
- forward path
- reverse path

For switch:
- address
- hostname
- controller

For port we don't need any additional fields.

For link:
- actual status
- max bandwidth
- default bandwidth
- available bandwidth
- cost
- latency

# rough plan

- [x] Design & POC (10d)
- [x] Implement (5-10d)
- [x] Review and fix (2-3d)

Total: 21d

**Comment by Settis** [comment]
@carmine, could you please take a look at the proposal. I'm interested in your comments.

**Comment by carmine** [comment]
@Settis - A few comments:

1. Original focus was on flow history, but I like the expanded set of objects to keep some history. However, let's do this iteratively - ie publish the Flow stuff first, then move on to the next item, etc.
2. History collection - it should aggregate history from the workflow manager as well .. ie, each step of flow creation should go into the history table. It seems that your examples cover this (ie user initiated port down, and/or the port down due to network event). It is just that the initial description didn't seem 100% clear.
3. Maybe this isn't part of this service exactly, but some thought should be given to retention (ie how long to store in the DB). This might vary by event type.

The other fields look reasonable at the design level.
