### ISSUE TITLE
Deleting a flow on a blinking ISL sometimes leads to desync between TE and Flow topology 

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#1216]
1. Create a flow (in my case flow DID have ability to reroute to alt path)
2. Start blinking a port on one of the ISLs that are used by the flow (in order to issue reroutes)
3. While ISL is blinking delete the Flow via Northbound
**Expected:** Flow is completely removed from the system. Reroutes stop
**Actual:** Flow is no longer returned from Northbound, but it is actually present in Neo4j.

Note: This seems to be a race condition, so issue may not reproduce from the first try. Going to link this issue to a test script later.
Note2: Was also able to receive a ghost flow which is only present in CacheTpology (not present in Neo or returned from NB)

**Comment by nikitacherevko** [comment]
Here is some useful messages from logs:

`August 29th 2018, 11:23:56.143 READ MESSAGE 
{"clazz":"org.openkilda.messaging.info.InfoMessage","destination":"TOPOLOGY_ENGINE","payload":{"clazz":"org.openkilda.messaging.info.flow.FlowInfoData, "payload":{"forward":{"flowid":"29Aug112326", "state":"ALLOCATED", ...}, ..., "operation":"UPDATE"}}
August 29th 2018, 11:23:56.140 READ MESSAGE {"clazz":"org.openkilda.messaging.info.InfoMessage","destination":"TOPOLOGY_ENGINE","payload":{"clazz":"org.openkilda.messaging.info.flow.FlowInfoData","payload":{"forward":{"flowid":"29Aug112326", "state":"ALLOCATED", ...}, ..., "operation":"DELETE"}}`

As you can noticed we've received update/reroute request after actual flow delete request, so it is might be the root cause.

**Comment by rtretyak** [comment]
This issue may be now outdated due to H&S changes in Kilda.

**Comment by pzakatov** [comment]
outdated
