### ISSUE TITLE
new API: PATCH /flows/{flow_id}/meters. Update meters according to the current settings/policies

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1787]
# Purpose
The main purpose is to have the ability to update `burst` parameter according to the current configuration and configure a proper set of flags.

Also, this functionality could be reused if BW update required and it is available on the current path.

**Comment by Levitan** [comment]
Which model we must return from this API method?

**Comment by rtretyak** [comment]
@pzakatov Please give more details on this:
- Should we be able to set custom burst via query param? Like `PATCH /flows/{flow_id}/meters?burst=666`?
- Or should this operation be able to only update current meter values to our default policies (for cases when policies changed, but old flows remain using old policies), without specifying the custom burst size?

Asking because I'm a bit confused by implementation in #1873, which requires to specify burst manually during request.
CC @Levitan

**Comment by niksv** [comment]
Closed by #1873
