### ISSUE TITLE
Switch Bounces, Re-install Flows

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#184]
The Ingress and Egress flow rules should be re-installed if a switch comes back online. This will require some logic within either the WFM and/or FLOW topology to detect that a previous switch, with some state, has come back online.

The TransitFlows need some further analysis. The logic needs to determine if kilda re-routed a flow. Presumably the transit disappears from the both cache and neo4j if a flow has changed.  There are some flows that might not get re-flowed - eg if the only path is through the switch that went down.

**Comment by nikitacherevko** [comment]
@carmine can we just re-calculate flow in case of some switch goes up? I mean once one switch is up we can check whether fastest path is available and whether this switch will be using as transit?

So that's how I see this functionality:
1. CacheBolt checks whether switch had ingress/egress flows and if yes - re-create them again. If current switch was transit and the only one through whom flow was created we can just restore them from cache, because they weren't deleted.
2. Re-route all existing flows. The advantage of this approach is that we don't need store any history and states of flows. Disadvantages: we have to rebuild flows every time when any switch goes up.

**Comment by carmine** [comment]
Given enough compute, whenever a new switch comes up, we would recalculate all flows. But, at scale, we'd have to do something smarter to reduce the set of flows to those likely to be benefitted.

For now, we can simplify this and make sure that when we receive a switch down event, we make a copy of all flows impacted by this, and use that list when the switch comes back online.

For all ingress/egress, we can do as you suggest - reinstall from cache.

For all transit, we can start with flows that are still down, and see if we can reinstall those (ie keep in mind that the bandwidth may have been consumed, in which case a flow may not be able to be installed). After the down flows, we can look at the up flows and see if a better route is now available.

As part of switch down ..

1) If a switch goes offline / dies ... as part of that event .. the flow topology does a set of things:
a) All egress / ingress flows to be marked as down 
b) All transit flows - determine if there is an alternate path - and execute. This may need to be done one at a time due to bandwidth limitations (ie if bandwidth isn't oversubscribed)
c) For any transit flows not re-routable (either because of no other path or no bandwidth), mark them as down or blocked or whatever the right state is.
