### ISSUE TITLE
Bump storm and kafka verisons

### ISSUE THREAD

**Issue by rozdy** [telstra/open-kilda#2977]
We need to bump storm and kafka versions to fix security vulnerabilities.

Changes related to fix this issue can be found in `bump-storm-and-kafka-libs` branch.

**Comment by sergii-iakovenko** [comment]
The changes in #3519 cause the following issues:
-   All spouts have the "complete latency" and "acked" statistics equal to 0 (the stats can be checked in Storm UI). This may be caused by the "__acker" component, which lost associated streams ("__ack_init" and "__ack_ack") from bolts and spouts after the storm lib upgrade.

- On the development and staging environments, we observe uneven growth of "OTSDB ConsummerGroup Lag" (from 1 to 40 millions during 10 hours, then a steep drop) and gaps in metrics stored in OpenTSDB.

- There're Kafka related errors in the log: 
```
[Consumer clientId=consumer-6, groupId=floodlightrouter__SPEAKER_DISCO_KAFKA_SPOUT] Offset commit failed on partition kilda.speaker.disco.storm-1 at offset 192769769: The request timed out.
[Consumer clientId=consumer-4, groupId=floodlight_2] Offset commit failed on partition kilda.speaker.disco_2-0 at offset 138816474: The request timed out.
[Consumer clientId=consumer-4, groupId=floodlight_2] Offset commit failed on partition kilda.speaker.disco_2-1 at offset 80522141: The request timed out.
```

**Comment by sergii-iakovenko** [comment]
Please, check the changes in Storm 1.2.1 vs 1.1.0 related to Kafka Spout:
