### ISSUE TITLE
flowStatus is always "IN_PROGRESS" in flowHistory response

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#3038]
**Steps to reproduce**
1. create a flow
2. make sure that flow is `UP`
3. update the flow
4. check the flow history

**Actual result**
flowStatus is always "IN_PROGRESS" in flowHistory response

**Expected result**
status in the `stateBefore` section should be `UP` and in the `stateAfter` section should be `UP` too

**Comment by dmitrii-beliakov** [comment]
There is no field status in the current implementation. The problem is there, but is slightly different. 
Steps to reproduce:
1. Create a flow (make sure the flow is up)
2. look up for the history of that flow
expected: history contains forwardStatus: ACTIVE and reverseStatus: ACTIVE
actual result: history contains forwardStatus: IN PROGRESS and reverseStatus: IN PROGRESS

**Comment by dmitrii-beliakov** [comment]
I was not able to reproduce this issue with the update scenario.
