### ISSUE TITLE
Add "reflow_on_switch_activation" policy to TE

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#374]
SUMMARY: Add a policy variable that controls whether "try reflows for flows in down state" is called when a SWITCH ACTIVATION event is received.

FEATURES:
- [ ] This should be called after **sync_flows_on_activation** executes (ie ensure the switch has the rules we think it should have)
- [x] There should be a NB API to toggle this behavior.
- [x] Initial behavior is to try to reflow all flows in the down state

**Comment by nikitacherevko** [comment]
@carmine currently re-flow commands are generating in CacheTopology in storm. So probably that flag should be stored there.

**Comment by surabujin** [comment]
@carmine Regarding storing this "policy variable" - in memory storage is extremely bad practice. We need some external, persistent, easy to manage and use(from any of our service/language) storage. I propose to use redis(https://redis.io/). It is fast, atomic and easy to manage (I have a confirmation from infra team).

Later we can extend it's usage for other shared/persistent object used in kilda project.

Can we use redis for this dynamic/shared(it must be shared because we need more that one instance of our services) "policy variable"? (It will not lead to delay in implementation).

**Comment by surabujin** [comment]
implemented in https://github.com/telstra/open-kilda/pull/402
