### ISSUE TITLE
the reason, why a flow is not in the UP state, is missed in flowHistory

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#4049]
```
{
     "timestamp": 1612880987,
     "action": "Flow reroute completed",
     "details": "Flow reroute completed with status DEGRADED  and error null"
}
```

```
format("Flow reroute completed with status %s  and error %s", stateMachine.getNewFlowStatus(),
                            stateMachine.getErrorReason())
```

**NOTE:**
There are also two spaces between `flowState` and `and`

**Comment by dmitrii-beliakov** [comment]
I tried to follow the steps from MaxLatencySpec.groovy from the test case that includes this error message. But I get different result. Either I cannot get to this point because the path cannot be calculated, or the error message is present. 
Probably there is some other parameter in the environment that makes this issue possible. However, I was not able to find it and reproduce the issue.

**Comment by dmitrii-beliakov** [comment]
I found the steps to reproduce this issue. I created a flow using a standard test topology between switches 1 and 2 using MAX_LATENCY strategy and having max_latency and max_latency_tier2 such that
latency between 1 and 2 directly < max_latency < sum of latencies between 1 and 2 through other switch
After the flow is created and is in state UP, I made sure it uses a direct link between 1 and 2. Then, I took down the port 1 on switch 1, disabling the ISL between 1 and 2. Then I executed the reroute for this flow. Then I can see the following action in the flow history:
```
                "action": "Flow reroute completed",
                "details": "Flow reroute completed with status DEGRADED  and error null",
```
