### ISSUE TITLE
Disabled feature still allows to affect cached flows 

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#501]
A flow creation request sent to NB with disabled "create_flow" feature is blocked in TE, but still affects 
CrudBolt caches. As the result NB returns a phantom flow: which doesn't exist in DB, but kept in the cache.

Steps to reproduce:
- The controller with disable "create_flow" feature is up. Mininet can be used (i.e. make up-test-mode)
- `: make -f base/hacks/usecase/flow.crud.make deploy-flow-topo`
- `: make -f base/hacks/usecase/flow.crud.make deploy-flows`
- Check the difference of `http://localhost:8088/api/v1/flows` and DB.

**Comment by abochkarev** [comment]
@sergii-iakovenko @nikitamarchenko This scenario is reproducible, but there is no expected behavior. What are we planning to see if the feature is not enabled: some exception with the message, i.e  "Please enable create flow feature" or just silent execution as it was before, but w/o creating a phantom flow? Let's discuss it.

**Comment by abochkarev** [comment]
According to the internal discussion with @sergii-iakovenko @nikitacherevko was decided to postpone this bug fixing. There are a couple of reasons for it:
1) not clear how important feature enabling at all;
2) there are plans to get rid of bolt caches;

**Comment by pzakatov** [comment]
outdated
