### ISSUE TITLE
org.openkilda.testing.service.lockkeeper.LockKeeperServiceImpl.knockoutSwitch() destroys hardware environment

### ISSUE THREAD

**Issue by pkazlenka** [telstra/open-kilda#5074]
Currently, when we try to simulate switch which is unavailable for floodlight on real hardware environment, switch becomes unconscious and doesn't allow to revive/validate/synchronize itself.
Find the root cause of the problem and fix the method to be able to run method on real environment/

**Comment by rtretyak** [comment]
> switch becomes unconscious and doesn't allow to validate/synchronize itself
Isn't this the whole point of knocking out the switch? 🤔

**Comment by pkazlenka** [comment]
> > switch becomes unconscious and doesn't allow to validate/synchronize itself
> 
> Isn't this the whole point of knocking out the switch? thinking

I've updated the description. Reviving HW switches doesn't work (or doesn't work every time). For the last two days we had a switch which left deactivated after revival and a switch which somehow chose wrong mgmt IP and was not available from GRPC. I see that this issue [comes from 2019](https://github.com/telstra/open-kilda/blob/49dc7cf975b3d44595e49c9329d72df4c435f87b/src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableFlowsSpec.groovy#L1267)
Please, ping me if you know better about the history of this problem and if it was solved or you have some clues on it.

**Comment by rtretyak** [comment]
I'm pretty sure that knockout actually used to work on HW env. Afair it took a little bit more time for switch to disconnect than on a virtual env and it could have messed with test timeouts a bit, but it worked.
So my thought process here would be:
1. Check iptables rules on relevant floodlights that switch tries to connect to but can't. If iptables in those floodlight containers contain rules from here https://github.com/telstra/open-kilda/blob/develop/src-python/lock-keeper/lockkeeper.py#L235 (or, probably, any other rules), then the 'revive' command didn't actually execute correctly and we should further investigate why. If iptables are clean, then, tbh, I don't see any valid reasons for switch not to connect to FL as expected. In this case I'd have checked FL logs for any obvious errors saying why certain switch cannot connect or further investigated possible faulty behavior in sw firmware, maybe tried it on 'previous' firmware version.
2. I can recall a problem with GRPC malfunctioning when switch switched between mgmt floodlights (I think it was due to fls being in different networks?), but I can't recall if there was any solution to that.

**Comment by pkazlenka** [comment]
False alarm. Seems like switches don't return from knockout very rarely. This issue can be reopened if we find a reliable way to reproduce an issue.
