### ISSUE TITLE
Harmonize HealthCheckSpecification and Env*Extension in functional tests

### ISSUE THREAD

**Issue by pkazlenka** [telstra/open-kilda#5162]
Right now in functional tests we have HealthCheckSpecification, which is run before each test spec and various environment preparement/cleanup extensions (https://github.com/telstra/open-kilda/blob/93e5ac87e5a91e600e1b3c9dd21d85157905e38a/src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env), which are run once per test run (verify this). 
Because all of them do more or less the same, it could be a good idea to not waste time on performing the same checks/fixes twice.

**Comment by rtretyak** [comment]
I'll try to explain the differences, up to you how to improve here:
1. HealthCheckSpecification is supposed to run only once for the whole test run, not before each test spec. The idea here was to verify overall system readiness to even begin any testing. I can't recall how it worked with parallel topologies, but looking at HealthCheckBaseSpecification it looks like the idea was that it will run only once overall, other 'islands' would wait until healthcheck is finished for the first island and then use its result (either success or error)
2. Hardware env cleanup is kind of an on-demand script supposed to fix a broken hardware env and make it ready for testing. No guarantees though, since hw env can be broken in countless unusual ways. It runs active actions trying to fix the env, while HCSpec runs only 'get' operations. If it didn't fix, the HealthCheckSpecification should stop further tests execution later.
3. Virtual env cleanup is a similar helper for local development. While EnvExtension will re-create labs (switches) between local runs, you still want to remove any additional contamination in database or other global configs not related to switches itself. done by this ext.
4. EnvExtension is responsible for initialisation of env. It does run some basic 'healthchecks' when creating virtual labs, but those checks are very basic, far less than HealthCheckSpec. It is also run _before_ any 'cleanup' extensions.

So the sequence is: EnvExtension inits env -> HwCleanup/VirtualCleanup takes active actions to fix env between different test sessions -> HealthCheckSpec runs verifications to check if provided env can be used for testing (once per test session, at least it was supposed to work like that 😁 ).

The healthCheck itself shouldn't have any noticeable performance impact in context of how long most of the tests run. If you are having performance issues, I suggest checking that this listener is turned off, since it will run a lot of 'env' verifications after every single test in the test run and was meant to be used for debugging only. https://github.com/telstra/open-kilda/blob/3d16bdd3b8aa4bf0e869ab22eafbd52b7e1334ac/src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/listeners/CleanupVerifierListener.groovy

**Comment by pkazlenka** [comment]
> I'll try to explain the differences, up to you how to improve here:
> 
>     1. HealthCheckSpecification is supposed to run only once for the whole test run, not before each test spec. The idea here was to verify overall system readiness to even begin any testing. I can't recall how it worked with parallel topologies, but looking at HealthCheckBaseSpecification it looks like the idea was that it will run only once overall, other 'islands' would wait until healthcheck is finished for the first island and then use its result (either success or error)
> 
>     2. Hardware env cleanup is kind of an on-demand script supposed to fix a broken hardware env and make it ready for testing. No guarantees though, since hw env can be broken in countless unusual ways. It runs active actions trying to fix the env, while HCSpec runs only 'get' operations. If it didn't fix, the HealthCheckSpecification should stop further tests execution later.
> 
>     3. Virtual env cleanup is a similar helper for local development. While EnvExtension will re-create labs (switches) between local runs, you still want to remove any additional contamination in database or other global configs not related to switches itself. done by this ext.
> 
>     4. EnvExtension is responsible for initialisation of env. It does run some basic 'healthchecks' when creating virtual labs, but those checks are very basic, far less than HealthCheckSpec. It is also run _before_ any 'cleanup' extensions.
> 
> 
> So the sequence is: EnvExtension inits env -> HwCleanup/VirtualCleanup takes active actions to fix env between different test sessions -> HealthCheckSpec runs verifications to check if provided env can be used for testing (once per test session, at least it was supposed to work like that grin ).
> 
> The healthCheck itself shouldn't have any noticeable performance impact in context of how long most of the tests run. If you are having performance issues, I suggest checking that this listener is turned off, since it will run a lot of 'env' verifications after every single test in the test run and was meant to be used for debugging only. https://github.com/telstra/open-kilda/blob/3d16bdd3b8aa4bf0e869ab22eafbd52b7e1334ac/src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/listeners/CleanupVerifierListener.groovy

Thank you for explanations. Actually, performance problems are out of our focus. We have significant problem with 'long' test builds stability, and attempt to bring environment to the 'shape' before each test class is intended to provide quick fix, while investigating 'what tests silently poison environment without failing themselves' should be the long-term goal.

**Comment by yuliiamir** [comment]
https://github.com/telstra/open-kilda/pull/5514

**Comment by yuliiamir** [comment]
The appropriate changes have been added in the scope of https://github.com/telstra/open-kilda/pull/5514,
