### ISSUE TITLE
BUG: adding link_props in create_isl is doing an append, not an equal

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#527]
The original code in putting link props (in the TPE Rest .. topology.py code base) used:

`SET i += lp`

This adds all properties in LP to I.  However, it is really an APPEND.  If the property already exists in i, then this will add to that property - ie for string, it will be a concatenation; for numbers, it'll be an addition.

These are the things that should be done to the code base:
- [ ] add a unit test that confirms the wrong behavior
- [ ] fix TPE / create_isl -- make sure it does an '=' for each property in the LP.  Suggestion: convert the existing query into a real object (ie py2neo relationship), then use dict update to add all props.
- [ ] fix TPER / topology.py -- the PUT operation is mostly correct ... whatever is being PUT will be added to both the LP and to the ISL.  However, if there are existing items in the LP, these won't be pushed to the ISL.  This is an edge case .. shouldn't be an issue .. but to be safe / complete .. the algorithm should be:  1) push properties to LP;  2) get all properties from LP;  3) use dict update to add to the ISL.  If the code is changed to use objects instead of queries, this should just work.

**Comment by surabujin** [comment]
I have a couple of questions
* why it is in TER and not in TE?
* why there is no any "white list" of allowed properties (and data type for this properties)? (there is only black list on disallowed properties)
* what is the goal(reason to appear) the link property node?
* now (when we don't remove any ISL) can we move data from link properties to ISL links?

**Comment by pzakatov** [comment]
please update ticket considering TE/TER removal

**Comment by surabujin** [comment]
TER is not a target of this ticket, because link_props handling was moved from TER into TE.
TE still have mentioned here "issue" https://github.com/telstra/open-kilda/blob/c496aa923d792289c2dcc7175381c1ad20d93353/services/topology-engine/queue-engine/topologylistener/messageclasses.py#L406

But according to Neo4j documentation https://neo4j.com/docs/developer-manual/3.4/cypher/clauses/set/#set-adding-properties-from-maps (and manual tests confirm behavior from documentation). So this issue can't be reproduced.

We can provide a test to prove correct behavior.

**Comment by rtretyak** [comment]
Already tested here
https://github.com/telstra/open-kilda/blob/1c1f78d4453576821991c5bbadfdc32b670934d8/services/src/atdd-staging/src/main/resources/features/northbound.feature#L56
Issue is not reproducible.
