### ISSUE TITLE
Zero Downtime - Data Path

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#54]
Confirm switches are not wiped when the controller comes up. If they are wiped, then change the code to not clear the rules when coming up. It should be a configuration option in FloodLight.

- [x] Day1. Check whether switches are not wiped.
- [x] Day2. Check whether switches are not wiped. Add configuration.
- [x] Day3. Add atdd

**Comment by carmine** [comment]
Estimate 1d. If an acceptance test doesn't already exist, it'd be good to add .. although I'm not sure how to best do this .. since we want to confirm an interaction between floodlight and the switches.

**Comment by nikitamarchenko** [comment]
5d

**Comment by nikitacherevko** [comment]
I suppose those changes may takes up to 2 days

**Comment by a-ovchinnikov** [comment]
2d to 3d, I'd say 2d is more like it.

**Comment by nikitacherevko** [comment]
I've added some new rules for switch and then stopped/restarted floodlight and after that my switch still have my rules, so I may confirm switches are not wiped. Will try find a way to make it configurable.

Besides, I have no idea how to write atdd tests for it, because it is not possible, if I'm not mistaken, to manage floodlight state from our tests.

**Comment by nikitacherevko** [comment]
We have two configuration properties for defining whether tables should be cleared up or not. More information is available here: [https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/9142325/Switch+Flow+Table+Configuration]

property clearTablesOnInitialHandshakeAsMaster is now YES
property clearTablesOnEachTransitionToMaster is NO

Since currently controller runs under role which is not MASTER our rules won't be wiped after restart. I suggest change first property to NO too, so we'll be sure that our rules will persist and nothing won't destroy them.

**Comment by carmine** [comment]
Agreed - the default for both should be NO.

Regarding how to test .. I suggest adding a test in ATDD .. as part of the test, restart the floodlight container (ie execute a CLI command through Java).
