### ISSUE TITLE
GUI: Graph: Victoria: Incorrect metrics value (max value)

### ISSUE THREAD

**Issue by yuliiamir** [telstra/open-kilda#5458]
There is a difference between the max value of the graphs for the same flow, but different sources (Victoria and OTSDB). It seems like an issue with the data used by GUI to represent the Victoria graph: API api/stats/victoria/flow.
Victoria (incorrect behaviour): 
![VictoriaIncorrectMetricsMaxValue](https://github.com/telstra/open-kilda/assets/53427842/ae4473dc-b821-4f5e-8b37-58dc7d67af99)

Direct call to Victoria (there is no 41.3 value):
vm:8428/prometheus/api/v1/query_range?query=rate(kilda.flow.packets)&step=10s&start=2023-10-27T13:30:59Z&end=2023-10-27T13:40:59Z
```
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"direction":"forward","flowid":"27Oct153047_086_whiterice2566","is_y_flow_subflow":"false"},"values":[[1698413530,"11.991127566251397"],[1698413540,"11.991127566251397"],[1698413550,"11.991127566251397"],[1698413560,"11.991127566251397"],[1698413570,"11.991127566251397"],[1698413580,"11.991127566251397"],[1698413590,"16.330547632153998"],[1698413600,"20.671705290555085"],[1698413610,"20.671705290555085"],[1698413620,"20.671705290555085"],[1698413630,"20.671705290555085"],[1698413640,"20.671705290555085"],[1698413650,"14.095542940975434"],[1698413660,"7.529568549058804"],[1698413670,"7.529568549058804"],[1698413680,"7.529568549058804"],[1698413690,"7.529568549058804"],[1698413700,"7.529568549058804"],[1698413710,"7.654018359638811"],[1698413720,"7.7787236883836615"],[1698413730,"7.7787236883836615"],[1698413740,"7.7787236883836615"],[1698413750,"7.7787236883836615"],[1698413760,"7.7787236883836615"],[1698413770,"8.078635385923667"],[1698413780,"8.377887706324222"],[1698413790,"8.377887706324222"],[1698413800,"8.377887706324222"],[1698413810,"8.377887706324222"],[1698413820,"8.377887706324222"],[1698413830,"8.377887706324222"]]},{"metric":{"direction":"reverse","flowid":"27Oct153047_086_whiterice2566","is_y_flow_subflow":"false"},"values":[[1698413530,"11.940547762191049"],[1698413540,"11.940547762191049"],[1698413550,"11.940547762191049"],[1698413560,"11.940547762191049"],[1698413570,"11.940547762191049"],[1698413580,"11.940547762191049"],[1698413590,"16.285883619790145"],[1698413600,"20.628536141662632"],[1698413610,"20.628536141662632"],[1698413620,"20.628536141662632"],[1698413630,"20.628536141662632"],[1698413640,"20.628536141662632"],[1698413650,"14.01935370946098"],[1698413660,"7.425907425907425"],[1698413670,"7.425907425907425"],[1698413680,"7.425907425907425"],[1698413690,"7.425907425907425"],[1698413700,"7.425907425907425"],[1698413710,"7.632824478368109"],[1698413720,"7.840128111029559"],[1698413730,"7.840128111029559"],[1698413740,"7.840128111029559"],[1698413750,"7.840128111029559"],[1698413760,"7.840128111029559"],[1698413770,"8.1185609975661"],[1698413780,"8.396641343462615"],[1698413790,"8.396641343462615"],[1698413800,"8.396641343462615"],[1698413810,"8.396641343462615"],[1698413820,"8.396641343462615"],[1698413830,"8.396641343462615"]]}]},"stats":{"seriesFetched": "2"}}
```

OTSDB(correct bahaviour):
![OSTDBCorrectMetricsValueMaxValue](https://github.com/telstra/open-kilda/assets/53427842/4ac3d211-0a57-46ff-9534-9b2e8476005f)

Direct call to OTSDB: 
vm:4242/api/query/q?start=2023/10/27-13:30:59&end=2023/10/27-13:40:59&m=sum:1s-avg-none:rate:kilda.flow.packets%7Bflowid=27Oct153047_086_whiterice2566,direction=*%7D

```
[{"metric":"kilda.flow.packets","tags":{"flowid":"27Oct153047_086_whiterice2566","is_y_flow_subflow":"false","direction":"reverse"},"aggregateTags":[],"dps":{"1698413529":11.916666666666666,"1698413588":20.949152542372882,"1698413649":7.311475409836065,"1698413708":7.966101694915254,"1698413769":8.262295081967213}},{"metric":"kilda.flow.packets","tags":{"flowid":"27Oct153047_086_whiterice2566","is_y_flow_subflow":"false","direction":"forward"},"aggregateTags":[],"dps":{"1698413529":11.983333333333333,"1698413589":20.65,"1698413649":7.533333333333333,"1698413708":7.898305084745763,"1698413768":8.383333333333333}}]
```

STR:
1. Create flow and generate traffic.
To reproduce the defect test  FlowCrudSpec "Valid #data.description has traffic and no rule discrepancies [#srcDstStr]" can be used. Add breakpoint before starting traff exam  and execute several time (6-8 during 2 min) traff generation+verification section
```
withPool {
                [exam.forward, exam.reverse].eachParallel { direction ->
                    def resources = traffExam.startExam(direction)
                    direction.setResources(resources)
                    assert traffExam.waitExam(direction).hasTraffic()
                }
            }
```
2. Go to the Kilda GUI and check Graph Victoria/OTSDB.

**Comment by IvanChupin** [comment]
These two graphs certainly look different and have slightly different data points. 
Although you tried to made a direct call to opentsdb and victoriaDb in order compare the result datasets, both requests were different from the ones that are used in kilda-GUI:
correct version for opentsdb direct call:
vm:4242/api/query/q?start=2023/10/27-13:30:59&end=2023/10/27-13:40:59&m=**sum:30s-avg**-none:rate:kilda.flow.packets%7Bflowid=27Oct153047_086_whiterice2566,direction=*%7D

correct version for victoria direct call:
vm:8428/prometheus/api/v1/query_range?query=**rate(sum(kilda.flow.packets{flowid='27Oct153047_086_whiterice2566', direction='forward'}) by (flowid,direction))&step=30s**&start=2023-10-27T13:30:59Z&end=2023-10-27T13:40:59Z

Anyway,  the main issue why we can see the difference in two graphs is because opentsdb minimum step for data aggregation is 1 minute, despite the requested 30 seconds, but victoriaDb could work with 30s step. As result you could see the difference.  Both graphs shows us the rate. The rate is a characteristic that shows us a speed of change for each step. formula to calculate the rate is the following: rate = (V2-V1)/(T2-T1). So that delta value divided by time delta. 
For example here is a graph example for victoria, **this graph represents only the points, not the rate of change**: Rate of change points represented on the right side of the screenshot
<img width="1011" alt="Screenshot 2023-10-30 at 15 32 44" src="https://github.com/telstra/open-kilda/assets/9297385/20aad9e5-1d8e-4b23-84f2-655f6b33c2ac">. 

And here is the picture for opentsdb, **this graph represent only the points, not the rate**:  Rate of change points represented on the right side of the screenshot
<img width="1364" alt="Screenshot 2023-10-30 at 15 46 31" src="https://github.com/telstra/open-kilda/assets/9297385/0fac7d08-3960-4204-a3b5-5f83b6f0905f">

So what I want to underline here is that because of different step (30sec vs 1 minute) we have different result for rate graphs. 
So that for victoria we calculate rate points like this: (910 - 256) / (30s) = 21.8
but  for the opentsdb (910 - 256) / (60s) = 10,9.

**Comment by niksv** [comment]
@IvanChupin but why we have different step? I thought opentsdb can have any downsample value. At least I can set any downsample in otsdb UI

**Comment by yuliiamir** [comment]
This issue should be closed as it is not a defect (all details  are in the comment above).
