### ISSUE TITLE
if ISL comes up, only initiate reroutes for all flows in "Down" state

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#577]

**Comment by nikitacherevko** [comment]
This functionality is implemented already, but we should test/fix it (perhaps it doesn't work now)

**Comment by pzakatov** [comment]
@rtretyak please validate this functionality

**Comment by rtretyak** [comment]
Tested on staging
1. Verified that no reroute event happens when ISL comes up for already 'Up' flows (even though there is a better path available after ISL comes up).
2. Verified that reroute does happen for 'Down' flows on any ISL coming Up in the system.
3. If the system is able to reroute the 'Down' flow - the flow becomes Up. Remains in 'Down' otherwise.
4. Verified the above behavior for 'Cached' flows. Cached, basically has no impact on this functionality. If the flow was 'Up' before becoming 'Cached', then no reroute happens; if the flow was 'Down', then Cached flow will try to reroute and change itself to Up/Down depending on reroute result.

Closing this issue
