### ISSUE TITLE
missed cache for cookie

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#630]
area: org.openkilda.wfm.topology.stats.metrics.FlowMetricGenBolt

Sequence:
1. switch has 2 rules with different cookies
2. delete an old cookie from the switch
3. call API "update flow" -> new cookie obtained, rules rebuilt

expect: stats cache with a new cookie
Actual: missed stats cache for cookie 

workaround: restart stats topology

**Comment by rtretyak** [comment]
Unable to reproduce. Used next steps:
1. Created a flow between sw1 and sw2 in order to have some rules installed on sw1
2. removed non-default rules from sw1 (tried both via NB and removing flow from table manually on switch)
3. Called Update for created flow
4. all rules are successfully reinstalled
Observe no messages of format "missed cache for sw {} cookie {}" or any over error/warn spam from Storm in Kibana.
Also tried to remove default rules on step2 with no luck
@pzakatov
