### ISSUE TITLE
ISL replug. Old ISL should be removed

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#725]
New behavior: 
1. we have switches  A, B, and C. and ISL A.1-B.1.
2. replug cable from B.1 to C.1
3. discover ISL A.1-C.1. 
4. Detect that on A.1 there is existing ISL, and remove it (completely, from everywhere).

Previously on step 4 we just mark old ISL as inactive.

Note:
1. when ISL got deleted, reroute event should be issued for affected flows. (check, because it is possible that no need for rerouts because they will be rerouted when port goes down when we unplug a cable)

Option:
1. introduce "removed" state to ISL object in Neo4j.

**Comment by surabujin** [comment]
If this change it supposed to fix ISL (re)discovery #720... it will not fix it. The root cause of (re)discovery issue - is in loosing coherency between DB(neo4j) and event(wfm) topology cache. So there is no any difference in deactivating and removing colliding ISLs.

If it is supposed to workaround GUI issues... this is not best way to solve this issue. Better fix it on GUI side.

**Comment by nikitacherevko** [comment]
ISL replug should work correctly with the latest changes.
What we have done:
- fixed WFM topology to detect cases when the destination switch/port is changed and notify about that TE/CacheTopology
- TE marks new (updated/moved) ISL as active and marks previous/outdated ISL as inactive (TE do not delete it from neo4j)
- Cache topology reacts on all these events related to moving ISL and initiates reroute events as usual (on ISL up/down)

Please note:
Perhaps we should modify our logic to deactivate previous ISL once we realize this ISL has been moved into another port/switch. In other words we have delay up 10 seconds between initiating flow reroute from the old ISL to a moved one (kilda defines ISL as inactive after 3 failed discovery packets, which is sending every 3 secs).
